/*
 * ==========================================================
 *  kitti_trace.h
 * ==========================================================
 *
 *  AUTO-GENERATED FILE
 *  Generated by : extract_kitti.py
 *
 *  Source:
 *      KITTI Vision Benchmark Suite
 *      Sequence: 2011_09_26_drive_0001_sync
 *
 *  Description:
 *      Forward obstacle distances extracted from
 *      KITTI LiDAR frames.
 *
 *  DO NOT EDIT THIS FILE MANUALLY
 *
 * ==========================================================
 */

#ifndef KITTI_TRACE_H
#define KITTI_TRACE_H

#include <stdint.h>

/* Number of processed frames */
#define KITTI_FRAMES 108

/* Safety thresholds (metres) */
#define KITTI_CRITICAL_DISTANCE   6.0f
#define KITTI_WARNING_DISTANCE   15.0f

/*
 * Forward obstacle distance for every KITTI frame.
 *
 * This array is generated automatically.
 *
 * Example values shown below.
 * Running extract_kitti.py replaces these
 * with the real dataset values.
 */

static const float kitti_distance[KITTI_FRAMES] =
{
    4.21f,
    4.18f,
    4.12f,
    4.30f,
    4.45f,
    14.72f,
    14.61f,
    13.95f,
    13.82f,
    13.75f,

    /* ............ */

    /* Remaining values are
       automatically generated
       by extract_kitti.py */

};

/* Current frame */

static uint32_t kitti_index = 0;

/*------------------------------------------------------*/
/* Return current obstacle distance                     */
/*------------------------------------------------------*/

static inline float kitti_get_distance(void)
{
    return kitti_distance[kitti_index];
}

/*------------------------------------------------------*/
/* Return current frame number                          */
/*------------------------------------------------------*/

static inline uint32_t kitti_get_frame(void)
{
    return kitti_index;
}

/*------------------------------------------------------*/
/* Move to next frame                                  */
/*------------------------------------------------------*/

static inline void kitti_next_frame(void)
{
    kitti_index++;

    if(kitti_index >= KITTI_FRAMES)
    {
        kitti_index = 0;
    }
}

/*------------------------------------------------------*/
/* Reset playback                                      */
/*------------------------------------------------------*/

static inline void kitti_reset(void)
{
    kitti_index = 0;
}

/*------------------------------------------------------*/
/* Check for Critical Zone                             */
/*------------------------------------------------------*/

static inline uint8_t kitti_is_critical(void)
{
    return
        (kitti_get_distance() < KITTI_CRITICAL_DISTANCE);
}

/*------------------------------------------------------*/
/* Check for Warning Zone                              */
/*------------------------------------------------------*/

static inline uint8_t kitti_is_warning(void)
{
    float d = kitti_get_distance();

    return
        (d >= KITTI_CRITICAL_DISTANCE &&
         d < KITTI_WARNING_DISTANCE);
}

/*------------------------------------------------------*/
/* Check for Safe Zone                                 */
/*------------------------------------------------------*/

static inline uint8_t kitti_is_safe(void)
{
    return
        (kitti_get_distance() >=
         KITTI_WARNING_DISTANCE);
}

#endif