/*
 * kitti_trace.h
 * ─────────────────────────────────────────────
 * Real World Sensor Data for CERTOX RTOS
 * Auto-generated by extraction/extract_kitti.py
 *
 * Source  : KITTI Autonomous Driving Dataset
 * Sequence: 2011_09_26_drive_0001
 * Citation: Geiger et al. IEEE CVPR 2013
 * URL     : cvlibs.net/datasets/kitti
 *
 * Dataset Statistics:
 * Frames     : 108
 * Critical   : 24 frames below 6m
 * Caution    : 77 frames 6m to 15m
 * Safe       :  7 frames above 15m
 * Departures :  7 lane departure events
 * ─────────────────────────────────────────────
 */

#ifndef KITTI_TRACE_H
#define KITTI_TRACE_H

/* Total real KITTI frames */
#define KITTI_FRAMES 108

/* Distance zone thresholds in meters */
#define KITTI_CRITICAL  6.0f   /* Brake NOW  */
#define KITTI_CAUTION   15.0f  /* Alert only */

/*
 * Real radar distances from KITTI LiDAR
 * Extracted from velodyne point cloud files
 * Original values in cm divided by 10
 * to give automotive range in meters
 *
 * Zone breakdown:
 * Below 6m   → CRITICAL → emergency brake
 * 6m to 15m  → CAUTION  → driver alert
 * Above 15m  → SAFE     → normal driving
 */
static float kitti_distances[KITTI_FRAMES] = {
    4.1f,  4.1f,  4.1f,  4.2f,  4.2f,  4.5f,
    14.7f, 14.6f, 14.6f, 14.3f, 13.7f, 14.4f,
    13.6f, 4.8f,  4.6f,  4.5f,  4.4f,  4.3f,
    4.2f,  4.2f,  4.1f,  4.0f,  4.0f,  4.2f,
    14.3f, 14.1f, 13.7f, 13.8f, 4.4f,  13.8f,
    13.8f, 13.6f, 14.7f, 14.5f, 13.7f, 13.5f,
    4.2f,  14.2f, 14.6f, 13.8f, 14.4f, 14.7f,
    14.2f, 14.6f, 14.1f, 14.4f, 14.4f, 14.5f,
    14.4f, 14.4f, 14.6f, 13.7f, 14.5f, 14.6f,
    14.2f, 14.7f, 14.7f, 14.6f, 14.7f, 14.5f,
    14.0f, 14.2f, 14.2f, 14.3f, 14.4f, 14.5f,
    14.3f, 14.2f, 13.6f, 14.4f, 14.4f, 14.6f,
    14.4f, 13.8f, 14.6f, 13.6f, 14.3f, 14.5f,
    14.5f, 14.4f, 13.9f, 14.2f, 14.0f, 14.5f,
    13.8f, 13.9f, 14.6f, 14.5f, 14.5f, 14.5f,
    14.5f, 14.4f, 14.4f, 13.5f, 13.7f, 14.1f,
    13.9f, 13.7f, 14.5f, 14.4f, 13.6f, 14.1f,
    14.7f, 14.5f, 13.9f, 14.3f, 13.9f, 54.5f
};

/*
 * Real lane status from KITTI camera data
 * Derived from lateral acceleration in oxts
 * 1.0 = Lane OK       (car inside lane)
 * 0.0 = Lane Departure (car drifting out)
 */
static float kitti_lanes[KITTI_FRAMES] = {
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 1.0f, 1.0f, 1.0f, 0.0f,
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 1.0f, 1.0f, 1.0f, 0.0f,
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 1.0f, 1.0f, 0.0f, 1.0f,
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 1.0f, 0.0f, 1.0f, 1.0f,
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    0.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 1.0f, 1.0f, 1.0f, 0.0f,
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    0.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 1.0f, 1.0f
};

/* Current frame index */
static int kitti_index = 0;

/*
 * kitti_get_distance()
 * Returns current real radar distance
 * in meters from KITTI LiDAR data
 */
static inline float kitti_get_distance(void) {
    return kitti_distances[
        kitti_index % KITTI_FRAMES
    ];
}

/*
 * kitti_get_lane()
 * Returns current real lane status
 * 1.0 = Lane OK
 * 0.0 = Lane Departure
 */
static inline float kitti_get_lane(void) {
    return kitti_lanes[
        kitti_index % KITTI_FRAMES
    ];
}

/*
 * kitti_advance()
 * Move to next KITTI frame
 * Call once per radar task cycle (20ms)
 */
static inline void kitti_advance(void) {
    kitti_index =
        (kitti_index + 1) % KITTI_FRAMES;
}

/*
 * kitti_reset()
 * Reset to first frame
 * Call at start of each test scenario
 */
static inline void kitti_reset(void) {
    kitti_index = 0;
}

/*
 * kitti_get_index()
 * Returns current frame number
 */
static inline int kitti_get_index(void) {
    return kitti_index;
}

#endif /* KITTI_TRACE_H */
