/*
 * kitti_trace.h
 * Auto-generated by extraction/extract_kitti.py
 * DO NOT EDIT MANUALLY
 *
 * Source  : KITTI Dataset
 * Sequence: 2011_09_26_drive_0001
 * Citation: Geiger et al. IEEE CVPR 2013
 * URL     : cvlibs.net/datasets/kitti
 *
 * Frames    : 108
 * Critical  : 19 frames below 6m
 * Caution   : 88 frames 6m to 15m
 * Safe      : 1 frames above 15m
 * Departures: 8 lane events
 */

#ifndef KITTI_TRACE_H
#define KITTI_TRACE_H

#include <stdint.h>

#define KITTI_FRAMES 108

/* Distance thresholds */
#define KITTI_CRITICAL  6.0f
#define KITTI_CAUTION  15.0f

/* Original KITTI values in centimeters */
static uint32_t kitti_radar_cm[KITTI_FRAMES] = {
    41, 41, 41, 42, 42, 45, 147, 146, 
    146, 143, 137, 144, 136, 48, 46, 45, 
    44, 43, 42, 42, 41, 40, 40, 42, 
    143, 141, 137, 138, 44, 138, 138, 136, 
    147, 145, 137, 135, 42, 142, 146, 138, 
    144, 147, 142, 146, 141, 144, 144, 145, 
    144, 144, 146, 137, 145, 146, 142, 147, 
    147, 146, 147, 145, 140, 142, 142, 143, 
    144, 145, 143, 142, 136, 144, 144, 146, 
    144, 138, 146, 136, 143, 145, 145, 144, 
    139, 142, 140, 145, 138, 139, 146, 145, 
    145, 145, 145, 144, 144, 135, 137, 141, 
    139, 137, 145, 144, 136, 141, 147, 145, 
    139, 143, 139, 545
};

/* Converted to meters (cm / 10) */
/* Critical <6m  Caution 6-15m  Safe >15m */
static float kitti_distances[KITTI_FRAMES] = {
    4.1f, 4.1f, 4.1f, 4.2f, 4.2f, 4.5f, 14.7f, 14.6f, 
    14.6f, 14.3f, 13.7f, 14.4f, 13.6f, 4.8f, 4.6f, 4.5f, 
    4.4f, 4.3f, 4.2f, 4.2f, 4.1f, 4.0f, 4.0f, 4.2f, 
    14.3f, 14.1f, 13.7f, 13.8f, 4.4f, 13.8f, 13.8f, 13.6f, 
    14.7f, 14.5f, 13.7f, 13.5f, 4.2f, 14.2f, 14.6f, 13.8f, 
    14.4f, 14.7f, 14.2f, 14.6f, 14.1f, 14.4f, 14.4f, 14.5f, 
    14.4f, 14.4f, 14.6f, 13.7f, 14.5f, 14.6f, 14.2f, 14.7f, 
    14.7f, 14.6f, 14.7f, 14.5f, 14.0f, 14.2f, 14.2f, 14.3f, 
    14.4f, 14.5f, 14.3f, 14.2f, 13.6f, 14.4f, 14.4f, 14.6f, 
    14.4f, 13.8f, 14.6f, 13.6f, 14.3f, 14.5f, 14.5f, 14.4f, 
    13.9f, 14.2f, 14.0f, 14.5f, 13.8f, 13.9f, 14.6f, 14.5f, 
    14.5f, 14.5f, 14.5f, 14.4f, 14.4f, 13.5f, 13.7f, 14.1f, 
    13.9f, 13.7f, 14.5f, 14.4f, 13.6f, 14.1f, 14.7f, 14.5f, 
    13.9f, 14.3f, 13.9f, 54.5f
};

/* Lane status */
/* 1.0=OK  0.0=Departure */
static float kitti_lanes[KITTI_FRAMES] = {
    0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 
    0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 
    0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 
    0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f, 1.0f, 1.0f
};

/* Current frame index */
static int kitti_index = 0;

/*
 * kitti_init()
 * Call once in main()
 * before starting scheduler
 */
static inline void kitti_init(void) {
    kitti_index = 0;
}

/* Get distance in meters */
static inline float kitti_get_distance(void) {
    return kitti_distances[
        kitti_index % KITTI_FRAMES
    ];
}

/* Get lane status */
static inline float kitti_get_lane(void) {
    return kitti_lanes[
        kitti_index % KITTI_FRAMES
    ];
}

/* Advance to next frame */
static inline void kitti_advance(void) {
    kitti_index =
        (kitti_index + 1) % KITTI_FRAMES;
}

/* Reset to frame 0 */
static inline void kitti_reset(void) {
    kitti_index = 0;
}

/* Get current frame */
static inline int kitti_get_index(void) {
    return kitti_index;
}

#endif /* KITTI_TRACE_H */
