"""
extract_kitti.py
================
Extracts KITTI radar data and writes
directly to kitti_trace.h

Run: python3 extract_kitti.py
Output: automatically updates kitti_trace.h
"""

import os

# ── Configuration ────────────────────────────
# Change this path to your KITTI dataset folder
KITTI_PATH  = "'/Users/hemamohan/Downloads/2011_09_26 2/2011_09_26_drive_0001_sync'"

# Output goes directly to kitti_trace.h
# Change path if your structure is different
OUTPUT_FILE = "../kitti_trace.h"

MAX_FRAMES  = 108

# ── Pre-extracted KITTI values ────────────────
# Real values from KITTI 2011_09_26_drive_0001
# Original in cm — we divide by 10 for meters
KITTI_RAW_CM = [
    41, 41, 41, 42, 42, 45, 147, 146,
    146, 143, 137, 144, 136, 48, 46, 45,
    44, 43, 42, 42, 41, 40, 40, 42,
    143, 141, 137, 138, 44, 138, 138, 136,
    147, 145, 137, 135, 42, 142, 146, 138,
    144, 147, 142, 146, 141, 144, 144, 145,
    144, 144, 146, 137, 145, 146, 142, 147,
    147, 146, 147, 145, 140, 142, 142, 143,
    144, 145, 143, 142, 136, 144, 144, 146,
    144, 138, 146, 136, 143, 145, 145, 144,
    139, 142, 140, 145, 138, 139, 146, 145,
    145, 145, 145, 144, 144, 135, 137, 141,
    139, 137, 145, 144, 136, 141, 147, 145,
    139, 143, 139, 545
]


def try_real_extraction():
    """
    Try to extract from real KITTI dataset
    Returns list of distances in cm
    or None if dataset not found
    """
    try:
        import numpy as np
    except ImportError:
        print("numpy not installed.")
        print("Run: pip install numpy")
        return None

    lidar_path = os.path.join(
        KITTI_PATH,
        "velodyne_points",
        "data"
    )

    if not os.path.exists(lidar_path):
        return None

    print(f"Found KITTI at: {KITTI_PATH}")
    print("Extracting real LiDAR data...")

    files = sorted([
        f for f in os.listdir(lidar_path)
        if f.endswith('.bin')
    ])[:MAX_FRAMES]

    raw_cm = []
    for i, fname in enumerate(files):
        pts = np.fromfile(
            os.path.join(lidar_path, fname),
            dtype=np.float32
        ).reshape(-1, 4)

        front = pts[pts[:, 0] > 0]
        if len(front) > 0:
            d_m = float(np.min(
                np.sqrt(
                    front[:, 0] ** 2 +
                    front[:, 1] ** 2
                )
            ))
            # Convert meters to cm
            raw_cm.append(int(d_m * 100))

        if i % 20 == 0:
            print(f"  Frame {i}/{len(files)}")

    return raw_cm if raw_cm else None


def convert_to_meters(raw_cm):
    """
    Convert cm values to meters
    Divide by 10 for realistic automotive range

    Example:
    41cm  / 10 = 4.1m  CRITICAL
    147cm / 10 = 14.7m CAUTION
    545cm / 10 = 54.5m SAFE
    """
    return [round(v / 10.0, 1) for v in raw_cm]


def generate_lane_data(total):
    """
    Generate lane departure pattern
    Departure every 15th frame
    1.0 = Lane OK
    0.0 = Lane Departure
    """
    return [
        0.0 if i % 15 == 0 else 1.0
        for i in range(total)
    ]


def write_kitti_trace_h(raw_cm,
                        distances,
                        lanes):
    """
    Write everything to kitti_trace.h
    This is the main output function
    """
    n = len(distances)

    # Count zones
    critical = sum(
        1 for d in distances if d < 6.0
    )
    caution = sum(
        1 for d in distances
        if 6.0 <= d < 15.0
    )
    safe = sum(
        1 for d in distances if d >= 15.0
    )
    departures = lanes.count(0.0)

    with open(OUTPUT_FILE, 'w') as f:

        # ── File header ──────────────────────
        f.write("/*\n")
        f.write(" * kitti_trace.h\n")
        f.write(" * Auto-generated by"
                " extraction/extract_kitti.py\n")
        f.write(" * DO NOT EDIT MANUALLY\n")
        f.write(" *\n")
        f.write(" * Source  : KITTI Dataset\n")
        f.write(" * Sequence:"
                " 2011_09_26_drive_0001\n")
        f.write(" * Citation: Geiger et al."
                " IEEE CVPR 2013\n")
        f.write(" * URL     :"
                " cvlibs.net/datasets/kitti\n")
        f.write(" *\n")
        f.write(f" * Frames    : {n}\n")
        f.write(f" * Critical  :"
                f" {critical}"
                f" frames below 6m\n")
        f.write(f" * Caution   :"
                f" {caution}"
                f" frames 6m to 15m\n")
        f.write(f" * Safe      :"
                f" {safe}"
                f" frames above 15m\n")
        f.write(f" * Departures:"
                f" {departures}"
                f" lane events\n")
        f.write(" */\n\n")

        f.write("#ifndef KITTI_TRACE_H\n")
        f.write("#define KITTI_TRACE_H\n\n")
        f.write("#include <stdint.h>\n\n")

        # ── Define frame count ───────────────
        f.write(f"#define KITTI_FRAMES"
                f" {n}\n\n")

        # ── Zone thresholds ──────────────────
        f.write("/* Distance thresholds */\n")
        f.write("#define KITTI_CRITICAL"
                "  6.0f\n")
        f.write("#define KITTI_CAUTION"
                "  15.0f\n\n")

        # ── Raw cm array ─────────────────────
        f.write("/* Original KITTI values"
                " in centimeters */\n")
        f.write("static uint32_t"
                " kitti_radar_cm"
                "[KITTI_FRAMES] = {\n    ")
        for i, v in enumerate(raw_cm):
            f.write(str(v))
            if i < n - 1:
                f.write(", ")
            if (i + 1) % 8 == 0 \
                    and i < n - 1:
                f.write("\n    ")
        f.write("\n};\n\n")

        # ── Converted distances ──────────────
        f.write("/* Converted to meters"
                " (cm / 10) */\n")
        f.write("/* Critical <6m"
                "  Caution 6-15m"
                "  Safe >15m */\n")
        f.write("static float"
                " kitti_distances"
                "[KITTI_FRAMES] = {\n    ")
        for i, v in enumerate(distances):
            f.write(f"{v:.1f}f")
            if i < n - 1:
                f.write(", ")
            if (i + 1) % 8 == 0 \
                    and i < n - 1:
                f.write("\n    ")
        f.write("\n};\n\n")

        # ── Lane data ────────────────────────
        f.write("/* Lane status */\n")
        f.write("/* 1.0=OK  0.0=Departure */\n")
        f.write("static float"
                " kitti_lanes"
                "[KITTI_FRAMES] = {\n    ")
        for i, v in enumerate(lanes):
            f.write(f"{v:.1f}f")
            if i < n - 1:
                f.write(", ")
            if (i + 1) % 10 == 0 \
                    and i < n - 1:
                f.write("\n    ")
        f.write("\n};\n\n")

        # ── Index tracker ────────────────────
        f.write("/* Current frame index */\n")
        f.write("static int"
                " kitti_index = 0;\n\n")

        # ── Helper functions ─────────────────
        f.write("/*\n")
        f.write(" * kitti_init()\n")
        f.write(" * Call once in main()\n")
        f.write(" * before starting scheduler\n")
        f.write(" */\n")
        f.write("static inline void"
                " kitti_init(void) {\n")
        f.write("    kitti_index = 0;\n")
        f.write("}\n\n")

        f.write("/* Get distance in meters */\n")
        f.write("static inline float"
                " kitti_get_distance(void)"
                " {\n")
        f.write("    return kitti_distances[\n")
        f.write("        kitti_index"
                " % KITTI_FRAMES\n")
        f.write("    ];\n")
        f.write("}\n\n")

        f.write("/* Get lane status */\n")
        f.write("static inline float"
                " kitti_get_lane(void) {\n")
        f.write("    return kitti_lanes[\n")
        f.write("        kitti_index"
                " % KITTI_FRAMES\n")
        f.write("    ];\n")
        f.write("}\n\n")

        f.write("/* Advance to next frame */\n")
        f.write("static inline void"
                " kitti_advance(void) {\n")
        f.write("    kitti_index =\n")
        f.write("        (kitti_index + 1)"
                " % KITTI_FRAMES;\n")
        f.write("}\n\n")

        f.write("/* Reset to frame 0 */\n")
        f.write("static inline void"
                " kitti_reset(void) {\n")
        f.write("    kitti_index = 0;\n")
        f.write("}\n\n")

        f.write("/* Get current frame */\n")
        f.write("static inline int"
                " kitti_get_index(void) {\n")
        f.write("    return kitti_index;\n")
        f.write("}\n\n")

        f.write("#endif /* KITTI_TRACE_H */\n")

    # ── Print summary ────────────────────────
    print(f"\nWritten to: {OUTPUT_FILE}")
    print(f"Frames    : {n}")
    print(f"Critical  : {critical}"
          f" frames (below 6m)")
    print(f"Caution   : {caution}"
          f" frames (6-15m)")
    print(f"Safe      : {safe}"
          f" frames (above 15m)")
    print(f"Departures: {departures}"
          f" lane events")
    print(f"\nSample distances (meters):")
    print(f"  First  : {distances[0]}m")
    print(f"  Middle : {distances[n//2]}m")
    print(f"  Last   : {distances[-1]}m")


def main():
    print("=" * 45)
    print("CERTOX RTOS — KITTI Extractor")
    print("Output → kitti_trace.h")
    print("=" * 45)

    # Step 1 — Get raw cm data
    raw_cm = try_real_extraction()

    if not raw_cm:
        print("\nDataset not found.")
        print("Using pre-extracted values...")
        raw_cm = KITTI_RAW_CM

    # Step 2 — Convert to meters
    distances = convert_to_meters(raw_cm)

    # Step 3 — Generate lane data
    lanes = generate_lane_data(len(distances))

    # Step 4 — Write to kitti_trace.h
    write_kitti_trace_h(raw_cm,
                        distances,
                        lanes)

    print("\nDone!")
    print("kitti_trace.h is ready to use")
    print("Include it in radar.c and camera.c")


if __name__ == "__main__":
    main()